// <auto-generated />
using System;
using LibraryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApp.Migrations
{
    [DbContext(typeof(LibraryAppDbContext))]
    [Migration("20260213213717_editDatabase")]
    partial class editDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("LibraryApp.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "G.R.R. Martin",
                            IsBorrowed = false,
                            Title = "A Game of Thrones (A Song of Ice and Fire #1)"
                        },
                        new
                        {
                            Id = 2,
                            Author = "G.R.R. Martin",
                            IsBorrowed = false,
                            Title = "A Clash of Kings (A Song of Ice and Fire #2)"
                        },
                        new
                        {
                            Id = 3,
                            Author = "G.R.R. Martin",
                            IsBorrowed = false,
                            Title = "A Storm of Swords (A Song of Ice and Fire #3)"
                        },
                        new
                        {
                            Id = 4,
                            Author = "G.R.R. Martin",
                            IsBorrowed = false,
                            Title = "A Feast for Crows (A Song of Ice and Fire #4)"
                        },
                        new
                        {
                            Id = 5,
                            Author = "G.R.R. Martin",
                            IsBorrowed = false,
                            Title = "A Dance with Dragons (A Song of Ice and Fire #5)"
                        },
                        new
                        {
                            Id = 6,
                            Author = "G.R.R. Martin",
                            IsBorrowed = false,
                            Title = "The Winds of Winter (A Song of Ice and Fire #6)"
                        },
                        new
                        {
                            Id = 7,
                            Author = "G.R.R. Martin",
                            IsBorrowed = false,
                            Title = "A Dream of Spring (A Song of Ice and Fire #7)"
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.K. Rowling",
                            IsBorrowed = false,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.K. Rowling",
                            IsBorrowed = false,
                            Title = "Harry Potter and the Chamber of Secrets"
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.K. Rowling",
                            IsBorrowed = false,
                            Title = "Harry Potter and the Prisoner of Azkaban"
                        },
                        new
                        {
                            Id = 11,
                            Author = "J.K. Rowling",
                            IsBorrowed = false,
                            Title = "Harry Potter and the Goblet of Fire"
                        },
                        new
                        {
                            Id = 12,
                            Author = "J.K. Rowling",
                            IsBorrowed = false,
                            Title = "Harry Potter and the Order of the Phoenix"
                        },
                        new
                        {
                            Id = 13,
                            Author = "J.K. Rowling",
                            IsBorrowed = false,
                            Title = "Harry Potter and the Half-Blood Prince"
                        },
                        new
                        {
                            Id = 14,
                            Author = "J.K. Rowling",
                            IsBorrowed = false,
                            Title = "Harry Potter and the Deathly Hallows"
                        },
                        new
                        {
                            Id = 15,
                            Author = "J.R.R. Tolkien",
                            IsBorrowed = false,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 16,
                            Author = "J.R.R. Tolkien",
                            IsBorrowed = false,
                            Title = "The Fellowship of the Ring (The Lord of the Rings #1)"
                        },
                        new
                        {
                            Id = 17,
                            Author = "J.R.R. Tolkien",
                            IsBorrowed = false,
                            Title = "The Two Towers (The Lord of the Rings #2)"
                        },
                        new
                        {
                            Id = 18,
                            Author = "J.R.R. Tolkien",
                            IsBorrowed = false,
                            Title = "The Return of the King (The Lord of the Rings #3)"
                        });
                });

            modelBuilder.Entity("LibraryApp.Entities.LibraryUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1998, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrej",
                            LastName = "Štrba",
                            PasswordHash = "wcIksDzZvHtqhtd/XazkAZF2bEhc1V3EjK+ayHMzXW8=",
                            Role = "Admin",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1985, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            LastName = "Kováćová",
                            PasswordHash = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=",
                            Role = "User",
                            UserName = "User1"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1994, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Peter",
                            LastName = "Novák",
                            PasswordHash = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=",
                            Role = "User",
                            UserName = "User2"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1979, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lucia",
                            LastName = "Horvátová",
                            PasswordHash = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=",
                            Role = "User",
                            UserName = "User3"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2002, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Martin",
                            LastName = "Šimek",
                            PasswordHash = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=",
                            Role = "User",
                            UserName = "User4"
                        });
                });

            modelBuilder.Entity("LibraryApp.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BorrowedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowedFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BorrowedTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BorrowedByUserId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LibraryApp.Entities.Loan", b =>
                {
                    b.HasOne("LibraryApp.Entities.Book", "BorrowedBook")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApp.Entities.LibraryUser", "BorrowedByUser")
                        .WithMany("Loans")
                        .HasForeignKey("BorrowedByUserId");

                    b.Navigation("BorrowedBook");

                    b.Navigation("BorrowedByUser");
                });

            modelBuilder.Entity("LibraryApp.Entities.LibraryUser", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
